package edu.kit.ipd.sdq.kamp.core;

public enum ActivityType {
	ARCHITECTUREMODELDIFF,
	INTERNALMODIFICATIONMARK,
	IMPLEMENTATION_SOURCECODE,
	IMPLEMENTATION_METADATA,
	BUILDCONFIGURATION,
	BUILDEXECUTION,
	TESTDEVELOPMENT,
	TESTUPDATE,
	TESTEXECUTION, 
	RELEASECONFIGURATION,
	RELEASEEXECUTION,
	DEPLOYMENTCONFIGURATION,
	DEPLOYMENTEXECUTION
}
