package edu.kit.ipd.sdq.kamp.core;

public enum ActivityElementType {
	ASSEMBLYCONNECTOR,
	DATATYPE,
	COMPOSITEDATATYPE,
	COLLECTIONDATATYPE,
	INTERFACE,
	INTERFACESIGNATURE,
	BASICCOMPONENT, 
	COMPOSITECOMPONENT, 
	PROVIDEDROLE,
	PROVIDEDOPERATION,
	REQUIREDROLE,
	REQUIREDOPERATION,
	SOURCECODEFILES,
	METADATAFILES,
	BUILDCONFIGURATION,
	TESTCASE, 
	RELEASECONFIGURATION,
	DEPLOYMENTCONFIGURATION, 
}
